version: "3.5"

services:
  db:
    image: postgres:12.3
    container_name: google_scraper_db
    environment:
      - POSTGRES_DB=google_scraper_development
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
