version: '3.8'

services:
  db:
    image: postgres:12.3
    container_name: google-scraper_db
    environment:
      - POSTGRES_DB=google_scraper_development
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
