name: Deploy

on:
  workflow_run:
    workflows:
      - Test
    branches:
      - main
      - develop
      - chore/chore-2-setup-ci-cd
    types:
      - completed
  workflow_dispatch:

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  HEROKU_STAGING_APP: ${{ secrets.HEROKU_STAGING_APP }}
  HEROKU_PRODUCTION_APP: ${{ secrets.HEROKU_PRODUCTION_APP }}
  HEROKU_ACCOUNT_EMAIL: ${{ secrets.HEROKU_ACCOUNT_EMAIL }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.event.workflow_run.head_branch || github.ref }}

      - name: Deploy Production
        if: github.ref == 'refs/heads/main'
        uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_email: ${{secrets.HEROKU_ACCOUNT_EMAIL}}
          heroku_app_name: ${{secrets.HEROKU_PRODUCTION_APP}}

      - name: Deploy Staging
        if: github.ref == 'refs/heads/chore/chore-2-setup-ci-cd'
        uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_email: ${{secrets.HEROKU_ACCOUNT_EMAIL}}
          heroku_app_name: ${{secrets.HEROKU_STAGING_APP}}
