name: Deploy

on:
  workflow_run:
    workflows:
      - Test
    branches:
      - main
      - develop
      - chore/chore-2-setup-ci-cd
    types:
      - completed
  workflow_dispatch:

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  HEROKU_STAGING_APP: ${{ secrets.HEROKU_STAGING_APP }}
  HEROKU_PRODUCTION_APP: ${{ secrets.HEROKU_PRODUCTION_APP }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Deploy Production
        if: github.ref == 'refs/heads/main'
        run: |
          git remote add production https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_PRODUCTION_APP.git
          git push -f production origin/main:refs/heads/master

      - name: Deploy Staging
        if: github.ref == 'refs/heads/chore/chore-2-setup-ci-cd'
        run: |
          git remote add staging https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_STAGING_APP.git
          git push -f staging origin/chore/chore-2-setup-ci-cd:refs/heads/master
