name: Deploy

on:
  workflow_run:
    workflows:
      - Test
    branches:
      - main
      - develop
      - chore/chore-2-setup-ci-cd
    types:
      - completed
  workflow_dispatch:

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  HEROKU_STAGING_APP: ${{ secrets.HEROKU_STAGING_APP }}
  HEROKU_PRODUCTION_APP: ${{ secrets.HEROKU_PRODUCTION_APP }}
  HEROKU_ACCOUNT_EMAIL: ${{ secrets.HEROKU_ACCOUNT_EMAIL }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "google-scraper-staging"
          heroku_email: "carryall369@gmail.com"
          justlogin: true
      - run: heroku auth:whoami
