name: Deploy

on:
  workflow_run:
    workflows:
      - Test
    branches:
      - main
      - develop
      - chore/chore-2-setup-ci-cd
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_STAGING_APP: ${{ secrets.HEROKU_STAGING_APP }}
      HEROKU_PRODUCTION_APP: ${{ secrets.HEROKU_PRODUCTION_APP }}
      HEROKU_ACCOUNT_EMAIL: ${{ secrets.HEROKU_ACCOUNT_EMAIL }}

    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.8
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "google-scraper-staging"
          heroku_email: ${{ secrets.HEROKU_ACCOUNT_EMAIL }}
          justlogin: true
      - run: heroku auth:whoami

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Deploy Production
        if: github.ref == 'refs/heads/main'
        uses: akhileshns/heroku-deploy@v3.8.8
        with:
          heroku_api_key: $HEROKU_API_KEY
          heroku_app_name: $HEROKU_PRODUCTION_APP
          heroku_email: $HEROKU_ACCOUNT_EMAIL
          usedocker: true

      - name: Deploy Staging
        if: github.ref == 'refs/heads/chore/chore-2-setup-ci-cd'
        uses: akhileshns/heroku-deploy@v3.8.8
        with:
          heroku_api_key: $HEROKU_API_KEY
          heroku_app_name: $HEROKU_STAGING_APP
          heroku_email: $HEROKU_ACCOUNT_EMAIL
          usedocker: true
