name: Deploy

on:
  workflow_run:
    workflows:
      - Test
    branches:
      - main
      - develop
      - chore/chore-2-setup-ci-cd
    types:
      - completed
  workflow_dispatch:

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  HEROKU_STAGING_APP: ${{ secrets.HEROKU_STAGING_APP }}
  HEROKU_PRODUCTION_APP: ${{ secrets.HEROKU_PRODUCTION_APP }}
  HEROKU_ACCOUNT_EMAIL: ${{ secrets.HEROKU_ACCOUNT_EMAIL }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Deploy Production
        if: github.ref == 'refs/heads/main'
        uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: $HEROKU_API_KEY
          heroku_app_name: $HEROKU_PRODUCTION_APP
          heroku_email: "carryall369@gmail.com"
          usedocker: true

      - name: Deploy Staging
        if: github.ref == 'refs/heads/chore/chore-2-setup-ci-cd'
        uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "google-scraper-staging"
          heroku_email: "carryall369@gmail.com"
          justlogin: true

      - name: Print
        run: heroku auth:whoami
