name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: Setup Go environment
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x

      - name: Go Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29

      - name: Copy ENV file
        run: cp ".env.test" ".env"

      - name: Install dependency
        run: make test-dependency

      - name: Prepare assets
        run: make assets

      - name: Run test
        run: make test
