name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.18.x

      - name: Go Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.29

      - name: Create .env file
        run: cp ".env.test" ".env"

      - name: Install dependencies
        run: make install-dependencies

      - name: Run tests
        run: make test
