name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: Setup Go environment
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x

      - name: Copy ENV file
        run: cp ".env.example" ".env"

      - name: Run Go Lint
        run: make lint

      - name: Run test
        run: make test
